name: gusar_invoice_scanner
description: "Мобильный терминал приёмки товаров по накладным и чекам для сети Gusar (gusar.tj)"
publish_to: "none"
version: 1.0.6+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design System
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  # Camera & Scanning
  camera: ^0.11.0+2
  mobile_scanner: ^5.1.1
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  file_picker: ^8.0.7

  # Networking & API
  dio: ^5.5.0+1
  http: ^1.2.2

  # Local DB & Persistence (Offline-First)
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.2.3

  # Documents & Signing
  signature: ^5.4.1
  pdf: ^3.10.8
  printing: ^5.13.1
  share_plus: ^10.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

